name = "vendata-solutions"
account_id = "082a2346245ba30a6cd9efdaae07e205"
workers_dev = true
compatibility_date = "2026-01-13"

[build]
command = "npm run build"
upload = { 
    dir = "./dist/client"
}
