/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/$404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesPrecisionAutomationRouteImport } from './routes/services/precision-automation'
import { Route as ServicesCustomResourcesRouteImport } from './routes/services/custom-resources'
import { Route as ServicesActionableDataRouteImport } from './routes/services/actionable-data'
import { Route as Services404RouteImport } from './routes/services/$404'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/$404',
  path: '/$404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPrecisionAutomationRoute =
  ServicesPrecisionAutomationRouteImport.update({
    id: '/services/precision-automation',
    path: '/services/precision-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomResourcesRoute = ServicesCustomResourcesRouteImport.update({
  id: '/services/custom-resources',
  path: '/services/custom-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesActionableDataRoute = ServicesActionableDataRouteImport.update({
  id: '/services/actionable-data',
  path: '/services/actionable-data',
  getParentRoute: () => rootRouteImport,
} as any)
const Services404Route = Services404RouteImport.update({
  id: '/services/$404',
  path: '/services/$404',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services/$404': typeof Services404Route
  '/services/actionable-data': typeof ServicesActionableDataRoute
  '/services/custom-resources': typeof ServicesCustomResourcesRoute
  '/services/precision-automation': typeof ServicesPrecisionAutomationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services/$404': typeof Services404Route
  '/services/actionable-data': typeof ServicesActionableDataRoute
  '/services/custom-resources': typeof ServicesCustomResourcesRoute
  '/services/precision-automation': typeof ServicesPrecisionAutomationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services/$404': typeof Services404Route
  '/services/actionable-data': typeof ServicesActionableDataRoute
  '/services/custom-resources': typeof ServicesCustomResourcesRoute
  '/services/precision-automation': typeof ServicesPrecisionAutomationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$404'
    | '/about'
    | '/contact'
    | '/services/$404'
    | '/services/actionable-data'
    | '/services/custom-resources'
    | '/services/precision-automation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$404'
    | '/about'
    | '/contact'
    | '/services/$404'
    | '/services/actionable-data'
    | '/services/custom-resources'
    | '/services/precision-automation'
  id:
    | '__root__'
    | '/'
    | '/$404'
    | '/about'
    | '/contact'
    | '/services/$404'
    | '/services/actionable-data'
    | '/services/custom-resources'
    | '/services/precision-automation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  Services404Route: typeof Services404Route
  ServicesActionableDataRoute: typeof ServicesActionableDataRoute
  ServicesCustomResourcesRoute: typeof ServicesCustomResourcesRoute
  ServicesPrecisionAutomationRoute: typeof ServicesPrecisionAutomationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$404': {
      id: '/$404'
      path: '/$404'
      fullPath: '/$404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/precision-automation': {
      id: '/services/precision-automation'
      path: '/services/precision-automation'
      fullPath: '/services/precision-automation'
      preLoaderRoute: typeof ServicesPrecisionAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-resources': {
      id: '/services/custom-resources'
      path: '/services/custom-resources'
      fullPath: '/services/custom-resources'
      preLoaderRoute: typeof ServicesCustomResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/actionable-data': {
      id: '/services/actionable-data'
      path: '/services/actionable-data'
      fullPath: '/services/actionable-data'
      preLoaderRoute: typeof ServicesActionableDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$404': {
      id: '/services/$404'
      path: '/services/$404'
      fullPath: '/services/$404'
      preLoaderRoute: typeof Services404RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  Services404Route: Services404Route,
  ServicesActionableDataRoute: ServicesActionableDataRoute,
  ServicesCustomResourcesRoute: ServicesCustomResourcesRoute,
  ServicesPrecisionAutomationRoute: ServicesPrecisionAutomationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
